/*
 * gauge_face.h -- LVGL image descriptor for the Firebird water-temp
 * gauge face. 480x480 RGB565 true-color (no alpha), Pontiac-style
 * ole-school face. Raw pixel data lives in gauge_face_classic.c,
 * auto-generated by png_to_lvgl_c.py from pontiac_face_final.png.
 *
 * The face does NOT bake in a needle, pivot hub, digital readout, or
 * live warning arc -- those are LVGL widgets drawn on top so they
 * track the live temperature and the user-adjustable alarm setpoint.
 * The baked red 240..260 band on the artwork is aesthetic only.
 *
 * Only the "classic" symbol name is kept for continuity with the rest
 * of the code; the dual-style (classic/compact) system has been
 * retired in favor of a single Pontiac-themed face.
 */
#ifndef GAUGE_FACE_H
#define GAUGE_FACE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern const lv_img_dsc_t gauge_face_classic;

#ifdef __cplusplus
}
#endif

#endif /* GAUGE_FACE_H */
